name: omnisense
description: AI powered chatbot
version: 1.0.1+2
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  auto_route: ^6.0.5
  bloc: ^8.1.1
  cloud_firestore: ^4.5.0
  dart_openai: ^1.9.1
  dio: ^5.1.1
  dotenv: ^4.1.0
  firebase_app_check: ^0.1.2+1
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  flex_color_scheme: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_hicons: ^0.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_slidable: ^3.0.0
  font_awesome_flutter: ^10.4.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  hydrated_bloc: ^9.1.0
  intl: ^0.17.0
  line_icons: ^2.0.1
  lottie: ^2.3.2
  markdown_widget: ^2.1.0
  path_provider: ^2.0.14
  quickalert: ^1.0.1
  vibration: ^1.7.6

dev_dependencies:
  auto_route_generator: ^6.0.3
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  twitter_login_v2: ^0.0.3
  very_good_analysis: ^3.1.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
flutter_assets:
  assets_path: assets/
  output_path: lib/src/app/
  filename: assets.dart
  
  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - .env
